cwojtak/GatorSecurity

senior_project_dea-main/src/components/Login.js
senior_project_dea-main/src/components/Navbar.js
senior_project_dea-main/src/components/Profile.js

- Added routing to Edit Button on user profile page so clicking on the button goes to /userInfo page

Added routing to Edit Button

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/Login.js

Added the `delete` endpoint. Also updated a couple lines in `Login.js` that were flagged by vscode.

Add delete endpoint and made 2 updates to Login.js

---

senior_project_dea-main/src/App.js
senior_project_dea-main/src/components/Admin.js
senior_project_dea-main/src/components/Learn.js
senior_project_dea-main/src/components/Login.js
senior_project_dea-main/src/components/LoginBanner.js
senior_project_dea-main/src/components/Navbar.js
senior_project_dea-main/src/components/Profile.js
senior_project_dea-main/src/components/SignUp.js
senior_project_dea-main/src/components/Welcome.js

Fixed most of the warnings given by ESLint when reloading the web page. Added one or two comments about various code parts.

Removed Most Warnings and Made Some Comments

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/Login.js

Added ability to edit questions (PUT) and comments in server.js

Added ability to edit questions (PUT) and comments in server.js

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/Logout.js
senior_project_dea-main/src/components/Navbar.js
senior_project_dea-main/src/components/Profile.js
senior_project_dea-main/src/components/UserInfo.js

- Fixed first error message by changing class to className
- Fixed second error message by deleting eventKey={3} from NavDropdown
- Altered the code formatting of Navbar.js

Fixed Navbar.js Issues causing Console Errors

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/Logout.js
senior_project_dea-main/src/components/Profile.js
senior_project_dea-main/src/components/UserInfo.js

_**Frontend**_
Issue: The Edit Profile button on localhost:3000/myprofile links to localhost:3000/userInfo. A user's email and first name can be seen, but the information cannot be edited.
Current Fix: Added the ability for a user to input a new first and last name for the user's profile. The user can successfully edit those two fields and change those two attributes.
Known Issues: Experimented with altering the user's email and password on the page. However, altering those properties caused rendering issues due to how backend currently works, and the method seems insecure.
Suggestions: Create a separate page, form, and button for a user to be able to alter their email address or password, then log them out.
_**Backend**_
Issue: There is no endpoint in server.js to edit a user's profile …

Added ability for user to update information in frontend and backend

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/Learn.js
senior_project_dea-main/src/components/QuestionCRUD.js
senior_project_dea-main/src/components/TraditionalQuestion.js

-  Fixed console error about non-unique keys in QuestionCRUD.js
-  Changed for to htmlFor in QuestionCRUD.js
-  Commented out unused code in TraditionalQuestion.js and Learn.js to remove ESLint warnings
-  Removed an erroneous comment in server.js

Fixed QuestionCRUD.js Console Errors and Minor Bug Fixes

---

senior_project_dea-main/server/package-lock.json
senior_project_dea-main/server/package.json
senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/QuestionCRUD.js

Addresses issue #23 
Uses express-validator (please run npm install after pulling)

Add validation for creating new questions

---

senior_project_dea-main/src/components/Welcome.js

Add us to the Creators section of the welcome page

---

senior_project_dea-main/server/server.js
senior_project_dea-main/src/components/UserInfo.js

server.post("/userInfo") in server.js was changed. Fixed by replacing data.data with data.data.dbUserData on line 38 of UserInfo.js.

Fixed issue with editing User Information

---

senior_project_dea-main/src/components/QuestionCRUD.js
senior_project_dea-main/src/components/QuestionCard.js
senior_project_dea-main/src/components/QuestionEdit.js
senior_project_dea-main/src/components/QuestionForm.js

Added additional functionality to the CRUD page.
- Add new questions
- View existing questions
- Edit existing questions
- Delete existing questions

CRUD page features

---

senior_project_dea-main/README.md

I rewrote the `README.md` file to clarify the instructions and to make it easier for us to add node packages that we may install as we work on the project.

Readme update

---

senior_project_dea-main/server/controllers/questions.js
senior_project_dea-main/server/controllers/users.js
senior_project_dea-main/server/schemas.js
senior_project_dea-main/server/validators/questionValidator.js
senior_project_dea-main/src/App.js
senior_project_dea-main/src/components/questions/GameTraditional.js
senior_project_dea-main/src/components/questions/Learn.js
senior_project_dea-main/src/components/questions/NewGameTraditional.js
senior_project_dea-main/src/components/questions/QuestionCRUD.js
senior_project_dea-main/src/components/questions/QuestionCard.js
senior_project_dea-main/src/components/questions/QuestionEdit.js
senior_project_dea-main/src/components/questions/QuestionForm.js
senior_project_dea-main/src/components/questions/TraditionalQuestion.js
senior_project_dea-main/src/components/users/Profile.js

-Convert old traditional game page to a new, dynamically populated version
-New field added to TraditionalQuestionInfo collection called DisplayType - determines whether a traditional question is displayed on the traditional game or learn page
-Old page can still be found at /oldGame, to be deprecated soon
-Update game score on profile page
-The new traditional game page takes advantage of a lot of learn page logic, so make sure to check the trad. game page if you make any changes to the learn page or its endpoints.
Addresses #69

Dynamically Populate Traditional Game Page 

---

senior_project_dea-main/package-lock.json
senior_project_dea-main/package.json
senior_project_dea-main/src/components/Navbar.js

Added useState and useEffect in Navbar.js to check user privileges. If user has admin privileges, the user will have 'Admin Panel' and 'Question Editor' options under 'My Profile'.
Non-Admin
Admin

62 admin navbar options

---

senior_project_dea-main/server/routers/questions.js
senior_project_dea-main/server/routers/users.js
senior_project_dea-main/src/components/questions/GameAdventure.js
senior_project_dea-main/src/components/users/SignUp.js

- Data is successfully received from backend for CYOA questions
- Basic HTML is established to render options as buttons and display a template image
- Submit functions have been created to check if the option matches the correct answer
TODO:
- Page needs to be force updated whenever a user gets the question right
- Before update, update the counter by 1 to load next question on reload
- Force update
- CSS needs to be implemented to match the Presentation 1 specs
- Need to dynamically populate buttons to HTML page

Added partial functionality to CYOA page

---

senior_project_dea-main/public/index.html
senior_project_dea-main/src/components/questions/GameAdventure.js

- Fixed most issues from my previous pull request

Finished adding functionality to CYOA Question page

---

senior_project_dea-main/server/controllers/games.js
senior_project_dea-main/server/routers/games.js
senior_project_dea-main/src/components/users/Profile.js

Get all games count for profile page

---

senior_project_dea-main/server/controllers/games.js
senior_project_dea-main/server/routers/games.js
senior_project_dea-main/server/schemas.js
senior_project_dea-main/src/components/users/Profile.js

Changed schema structure and updated endpoints

Rework DND backend

---

senior_project_dea-main/cypress.config.ts
senior_project_dea-main/cypress/component/Login.cy.js
senior_project_dea-main/src/components/questions/Game.js
senior_project_dea-main/src/components/questions/GameAdventure.js
senior_project_dea-main/src/components/questions/dragDrop/DragNDrop.js

- Added temporary citation credited to Professor Resch for Drag and Drop Games image on the /game page
- Changed Traditional Games to Fill in the Blank Games
- Made an if else statement that removes Answer explanation: if there is not one associated with the question

Fixed minor issues

---

senior_project_dea-main/server/controllers/games.js
senior_project_dea-main/server/routers/games.js

Add methods to update/delete matching questions

---

senior_project_dea-main/server/controllers/questions.js
senior_project_dea-main/server/controllers/users.js

Reverts cwojtak/GatorSecurity#179

Revert "Security vulnerabilities patched according to fixes outlined by sonar cloud"

---

senior_project_dea-main/src/components/questions/Game.js
senior_project_dea-main/src/components/questions/GameAdventure.js
senior_project_dea-main/src/components/questions/Matching/Matching.js
senior_project_dea-main/src/components/questions/Matching/MatchingCard.js
senior_project_dea-main/src/components/questions/dragDrop/DragNDrop.js

- Added scoring to memory matching games
- Fixed font differences on the photo credit hyperlinks on the Games page
- Added GetConfig().SERVER_ADDRESS to the appropriate places in the code

Added scoring to MM games/Fixed font bug on Games page

---

senior_project_dea-main/src/components/questions/Matching/Matching.js

- Fixed issue where MM game was only displaying two cards. Now displays 8 cards
- Fixed issues with victory requirements

Fixed display issue with MM games

---

senior_project_dea-main/package-lock.json
senior_project_dea-main/package.json
senior_project_dea-main/src/components/users/Admin.js

Button added to Admin page to download student data as a CSV file. The CSV file will contain first name, last name, email, learn score, and game score. Under student, progress will be the totals for all question categories to be used in Excel computations for scoring.

Added functionality to download student progress from the Admin page

---

senior_project_dea-main/src/components/Navbar.js
senior_project_dea-main/src/components/questions/GameAdventure.js
senior_project_dea-main/src/components/questions/QuestionCRUD.js
senior_project_dea-main/src/components/questions/dragDrop/DragNDrop.js
senior_project_dea-main/src/components/users/Admin.js

- Changed post request on Navbar.js to check for the response instead of data, since a bad response does not yield data
- Added a useEffect to QuestionCRUD.js so the server wouldn't be called an infinite amount of times
- Changed the Download CSV button on admin page to orange

Fixed random issues with site

---

senior_project_dea-main/README.md

Please make sure everyone has tested locally on a fresh repo before merging these changes.

Update README.md - read description!
